### ISSUE TITLE
Website data missing

### ISSUE THREAD

**Issue by Maldark** [zmiguel/Eve-Reactions-Calculator#212] opened 2024-10-10 22:25 UTC
Hey,

Pricing data seems to be missing

![image](https://github.com/user-attachments/assets/d222e9f4-6979-4311-a8e2-796c97a89ab8)

**Comment by zmiguel** [comment] 2024-10-10 22:40
Hi @Maldark thanks for the report, it looks like the Fuzzworks Market API I use to get price data is returning all zeros. That itself is caused by ESI from CCP being faulty at the moment, unfortunately there's nothing I can do right now as I don't have anything checking if price is zero before replacing everything. 

I've restored the database to an earlier version now, but it will be overwritten by zeros again if ESI is not fixed in the meantime. 
I'll work on a fix for when this happens in the future.

**Comment by Maldark** [comment] 2024-10-10 22:42
Awesome thanks for the rapid response! I figured I'd let you know in case you hadn't noticed...

Can you tell me roughly how old this data is? Is it earlier today or weeks old?

**Comment by zmiguel** [comment] 2024-10-10 22:43
@Maldark it should be about 1h30m old

**Comment by zmiguel** [comment] 2024-10-11 09:28
The issue with the pricing API seems to be fixed now

**Closed by zmiguel** 2024-10-11 09:28 UTC
Labels: bug, Database, Workers
